travis:
  secure:
    BINSTAR_TOKEN: T4u/Mu750QQsC21dWFPpSH129/dofNmzOTUHwp6nX0kcigHmNhJXxJuh1HzRSoab8M3YmXrKl8cPQQVZwGgq1KdcGbnAm8ap0ufm5Vx8sl3K4mh8NOjMTuVkgmj7NDt7BNoHTYM31Uk7u3wMJuRdCZhP3vAjubdLfAIO/kMsy/b+jhQ39rPetSTrIz7py9p21j9TB7Da/b0tt6DJryDebihAwe74HVFaIihs+fNZaCdagbzMSMyfvUfd2S0VAOz8NGay3lOtNnu8HqUxFzK52hlI+ZgVfXCM2lGuT2RDo1kvxnFmSNk1QMBy4Dnxhnw4BNTgx0Y8kkwyyp8DI9VAq+RiAatu87FJNxeFGBFtX3ql08DfE3FeYDkSY9ozykI6TEgXkXd1sIrk3kPvyR4Jr1Fwme62l+rIfnM3ml9BOqoebYXSvTJmsVPVwdiFCgPdS+RVxSEqYTCjBe5YxIJoJJsi2k/Imz64H0qNEtcsqyyd3X1Jga1K0Ju5kNTfSJersC9Z1cISEuAhO9kS8KWN/+gziNbcqTNdoMDxgqw2HxyHMB2xQcZxQrVTaM8K1/kVO345VG3iZnC2JOy5ZfH9dwTFUHa27phEmAbLJoce8fPh0qF2UWHtio7f8NqIXmsvY1rdjA+3qLTNfP/mdUDDVW6ym5X8zqLRMirGZ7OMlHc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
