travis:
  secure:
    BINSTAR_TOKEN: I9hCRGnbPNB4iVe9HroAcpZMQu4kaBNdKIDoUdnemW5y7brlRXy5XACBojCKhAbCmIkgWU2Zy5zWeyOGAbyfOTDrDLGmO6PNgRJ9lUJycWxpMVCAQ7vUR7Cjy0zRSIIX8Xahvh77ouhXmCCJZlr4vN4jNaxEwDQ9z2eljvpmj+U4ogdQD8Wt0YxO97jvnv9RnUEiNM2ao0srKa5My4HMzUVt5O3dcTAyI88oUuLIkdUOT1ZCQiHxDBpH99A1rXBbFubFu7C8OVD3FGvrmu6p1exLB7SfhPbfcF5deonX9pna3zbaO7738ICbv179xu0kpKZlf9aXuGtnOgxXM34rnnFO3p49SpnP+jcQiPTrhS3YGTLMvZk3vPRXZiMQoENUXk3pGo9L9MLZS3syBG+xuP0fcFT5geSY+5eXF6DkZfnNO/kiVJSOoqeTow8WhDSlJaoQKbYwyAGK4c3fT315Cm/a5BUATvM5GvHa1famauXX+aRX0CuU9bwqN+bFrNFsVx0qWjT0/4zkVtgtetVu/f7ucOT19Y0GOGG65BBmPJnah46A4f2/rnNcbjMZzzLkMDOsO0u2hFwXMwBsB/YMeLH8X9HXkcoKg2POWwqzCHdZgPyW5kgCRx9RgYVYBXF6tnyOBcOUoFgAJ5/qydyuvX9pkIGdff26raJskhB+z9o=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
